chdir: /home/bitnami/apps/PixelCMS
environment: production
address: 0.0.0.0
port: 4000
timeout: 30
log: /home/bitnami/log/pixel_cms_prod_thin.log
pid: /home/bitnami/tmp/pixel_cms_prod_thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
servers: 3
daemonize: true